version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_NAME: dev
      DB_USER: dev
      DB_PASS: dev
      MIGRATION_DIR: /migrations
  db:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASS: dev
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data