version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DB: dev
      DB_USER: dev
      DB_PASS: dev
  db:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASS: dev
    ports:
      - 5432:5432
    logging:
      driver: none